apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: devops-webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: devops-webapp
        # Usamos la imagen que subiste a DockerHub (asegúrate de que richardcas7ro2 sea tu usuario)
        image: richardcas7ro/devops-webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/info
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
